### Contact Index
GET http://localhost:3000/contacts

### Contacts Show
GET http://localhost:3000/contacts/1

### Contact Create
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "Dell",
  "email": "Testdell@example.com",
  "phone_number": "3124445535"
}

### Contact Update

PATCH http://localhost:3000/contacts/1
Content-Type: application/json

{
  "phone_number": "3123334444"
}

### Contact Destroy
DELETE http://localhost:3000/contacts

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
